// export const customIcons = [
//     { '113': ['white-balance-sunny', 'moon-waning-crescent'] },
//     { '116': ['weather-partly-cloudy', 'weather-night-partly-cloudy'] },
//     { '119': ['cloud-outline', 'cloud-outline'] },
//     { '122': ['cloud-outline', 'cloud-outline'] },
//     { '143': ['weather-fog', 'weather-fog'] },
//     { '173': ['weather-partly-rainy', ''] },
//     { '179': ['weather-partly-snowy', ''] },
//     { '182': ['weather-partly-snowy-rainy', ''] },
//     { '': ['', ''] },
//     { '': ['', ''] },
//     { '': ['', ''] },
//     { '': ['', ''] },
//     { '': ['', ''] },
//     { '': ['', ''] },
//     { '': ['', ''] },

// ]
export const customIcons = {
    '1000': ['sun', 'uil uil-moon'],
    '1003': ['uil uil-cloud-sun', 'uil uil-cloud-moon'],
    '1006': ['uil uil-cloud', 'uil uil-cloud'],
    '1009': ['uil uil-clouds', 'uil uil-clouds'],
    '1030': ['uil uil-windy', 'uil uil-windy'],
    '1063': ['uil uil-cloud-sun-tear', 'uil uil-forecastcloud-moon-tear'],
    '1066': ['uil uil-cloud-sun-meatball', 'uil uil-cloud-moon-meatball'],
    '1069': ['uil-cloud-sun-hail', 'uil uil-cloud-moon-hail'],
    '1072': ['uil uil-windy', 'uil uil-windy'],
    '1087': ['uil uil-thunderstorm-sun', 'uil uil-thunderstorm-moon'],
    '1114': ['uil uil-cloud-meatball', 'uil uil-cloud-meatball'],
    '1117': ['uil uil-cloud-meatball', 'uil uil-cloud-meatball'],
    '1136': ['uil uil-windy', 'uil uil-windy'],
    '1147': ['uil uil-windy', 'uil uil-windy'],
    '1150': ['uil uil-cloud-showers-heavy', 'uil uil-cloud-showers-heavy'],
    '1153': ['uil uil-cloud-showers-heavy', 'uil uil-cloud-showers-heavy'],
    '1168': ['uil uil-windy', 'uil uil-windy'],
    '1171': ['uil uil-windy', 'uil uil-windy'],
    '1180': ['uil uil-cloud-sun-tear', 'uil uil-forecastcloud-moon-tear'],
    '1183': ['uil uil-cloud-rain', 'uil uil-cloud-rain'],
    '1186': ['uil uil-cloud-sun-tear', 'uil uil-forecastcloud-moon-tear'],
    '1189': ['uil uil-cloud-rain', 'uil uil-cloud-rain'],
    '1192': ['uil uil-cloud-rain-sun', 'uil uil-cloud-moon-showers'],
    '1195': ['uil uil-cloud-showers-heavy', 'uil uil-cloud-showers-heavy'],
    '1198': ['uil uil-cloud-drizzle', 'uil uil-cloud-drizzle'],
    '1201': ['uil uil-cloud-drizzle', 'uil uil-cloud-drizzle'],
    '1204': ['uil uil-cloud-sun-hail', 'uil uil-cloud-moon-hail'],
    '1207': ['uil uil-cloud-hail', 'uil uil-cloud-hail'],
    '1210': ['uil uil-cloud-sun-meatball', 'uil uil-cloud-moon-meatball'],
    '1213': ['uil uil-cloud-meatball', 'uil uil-cloud-meatball'],
    '1216': ['uil uil-cloud-sun-meatball', 'uil uil-cloud-moon-meatball'],
    '1219': ['uil uil-cloud-meatball', 'uil uil-cloud-meatball'],
    '1222': ['uil uil-cloud-sun-meatball', 'uil uil-cloud-moon-meatball'],
    '1225': ['uil uil-cloud-meatball', 'uil uil-cloud-meatball'],
    '1237': ['uil uil-cloud-hail', 'uil uil-cloud-hail'],
    '1240': ['uil uil-cloud-sun-tear', 'uil uil-forecastcloud-moon-tear'],
    '1243': ['uil uil-cloud-sun-rain-alt', 'uil uil-cloud-moon-rain'],
    '1246': ['uil uil-cloud-sun-rain-alt', 'uil uil-cloud-moon-rain'],
    '1249': ['uil-cloud-sun-hail', 'uil uil-cloud-moon-hail'],
    '1252': ['uil-cloud-sun-hail', 'uil uil-cloud-moon-hail'],
    '1255': ['uil uil-cloud-sun-meatball', 'uil uil-cloud-moon-meatball'],
    '1258': ['uil uil-cloud-sun-meatball', 'uil uil-cloud-moon-meatball'],
    '1261': ['uil uil-cloud-sun-meatball', 'uil uil-cloud-moon-meatball'],
    '1264': ['uil uil-cloud-sun-meatball', 'uil uil-cloud-moon-meatball'],
    '1273': ['uil uil-thunderstorm-sun', 'uil uil-thunderstorm-moon'],
    '1276': ['uil uil-thunderstorm', 'uil uil-thunderstorm'],
    '1279': ['uil uil-thunderstorm-sun', 'uil uil-thunderstorm-moon'],
    '1282': ['uil uil-thunderstorm', 'uil uil-thunderstorm'],
}